name: Build Go app and push to Azure

on:
  push:
    branches: [ azure-webapp ]
  pull_request:
    branches: [ azure-webapp ]

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    
    - name: Build
      run: go build -o build/go-app.exe -v
      
    - name: Deploy to Azure
      uses: Azure/webapps-deploy@v2
      with:
        # Name of the Azure Web App
        app-name: task-management-ac01
        # Applies to Web App only: Path to package or folder. *.zip, *.war, *.jar or a folder to deploy
        package: build/
        publish-profile: ${{ secrets.azureWebAppPublishProfile }}
